apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: {{ .Values.certificateName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    shihadeh.dev/sync-to-namespaces: {{ .Values.namespaces }}
spec:
  secretName: tls-{{ .Values.certificateName }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: {{ template "cert-manager-issuer.name" . }}-{{ .Values.letsencryptServer }}
  commonName: {{ .Values.certCommonName | quote }}
  dnsNames:
    {{- range .Values.extraCertDNSNames }}
    - {{ . | quote }}
    {{- end }}
