apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-issuer.labels" . | nindent 4 }}
type: Opaque
data:
  secret-access-key: {{ index .Values "AWSSecretAccessKey" | b64enc | quote }}
